layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 200
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

# social_media:
  linkedin: https://linkedin.com/in/satish-babariya/

topics:
  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png
    
  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/go/go.png
    
  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/swift/swift.png

